_-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.administradores
(
    id serial NOT NULL,
    nombre_usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    clave_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT administradores_pkey PRIMARY KEY (id),
    CONSTRAINT administradores_email_key UNIQUE (email),
    CONSTRAINT administradores_nombre_usuario_key UNIQUE (nombre_usuario)
);

CREATE TABLE IF NOT EXISTS public.palabras
(
    id serial NOT NULL,
    palabra character varying(100) COLLATE pg_catalog."default" NOT NULL,
    significado text COLLATE pg_catalog."default" NOT NULL,
    ejemplo text COLLATE pg_catalog."default",
    pronunciacion character varying(100) COLLATE pg_catalog."default",
    audio_url character varying(500) COLLATE pg_catalog."default",
    region_id integer,
    provincia_id integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT palabras_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provincias
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    region_id integer,
    CONSTRAINT provincias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.regiones
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT regiones_pkey PRIMARY KEY (id),
    CONSTRAINT regiones_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.usuario_favoritos
(
    usuario_id integer NOT NULL,
    palabra_id integer NOT NULL,
    added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuario_favoritos_pkey PRIMARY KEY (usuario_id, palabra_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nombre_usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    clave_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email),
    CONSTRAINT usuarios_nombre_usuario_key UNIQUE (nombre_usuario)
);

ALTER TABLE IF EXISTS public.palabras
    ADD CONSTRAINT palabras_provincia_id_fkey FOREIGN KEY (provincia_id)
    REFERENCES public.provincias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.palabras
    ADD CONSTRAINT palabras_region_id_fkey FOREIGN KEY (region_id)
    REFERENCES public.regiones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.provincias
    ADD CONSTRAINT provincias_region_id_fkey FOREIGN KEY (region_id)
    REFERENCES public.regiones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuario_favoritos
    ADD CONSTRAINT usuario_favoritos_palabra_id_fkey FOREIGN KEY (palabra_id)
    REFERENCES public.palabras (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuario_favoritos
    ADD CONSTRAINT usuario_favoritos_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;